version: "3.7"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cognito
    ports:
      - "5432:5432"
     # Redis In memory cache
  redis:
    image: redis:7.4
    ports:
      - '6379:6379'
    # AWS S3 emulator
  minio:
    image: bitnami/minio:latest
    ports:
      - '9444:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=s3user
      - MINIO_DEFAULT_BUCKETS=dummy-bucket
