name: Build module and deploy to Cloudfront

on:
  push:
    branches:
      - "master"

env:
  REPO_OWNER: dev-alianwar
  REPO_NAME: nestjs-github-actions-aws-ecs

jobs:
  setup:
    uses: dev-alianwar/nestjs-github-actions-aws-ecs/.github/workflows/setup.yml@master

  update-version:
    needs: setup
    uses: dev-alianwar/nestjs-github-actions-aws-ecs/.github/workflows/update-version.yml@master
    secrets:
      access_token: ${{ secrets.GH_PAT }}

  deploy:
    needs: [setup, update-version]
    uses: dev-alianwar/nestjs-github-actions-aws-ecs/.github/workflows/deploy.yml@master
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}        
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}       
      ECS_SERVICE:  ${{ secrets.ECS_SERVICE }}      
      ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
      