name: Test, Update Version, Build and Deploy

on:
  push:
    branches:
      - "master"

env:
  REPO_OWNER: dev-alianwar
  REPO_NAME: nextjs-githubactions-s3-cloudfront

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  update-version:
    needs: [setup, test, build]
    uses: dev-alianwar/nextjs-githubactions-s3-cloudfront/.github/workflows/update-version.yml@master
    secrets:
      access_token: ${{ secrets.GH_PAT }}
    with:
      dry_run: false
      is_master: true

  deploy:
    needs: [setup, build]
    uses: dev-alianwar/ci-cd-example/.github/actions/deploy@master
